version: "3.8"
services:
  invoice-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      # For paddle bug fixes
      - FLAGS_enable_pir_api=0
      - FLAGS_use_mkldnn=0
    volumes:
      - .:/app
      - paddle_model_cache:/root/.paddlex/official_models

volumes:
  paddle_model_cache:
